version: '3.7'
services:
 jenkins:
   image: jenkins
   container_name: jenkins
   build: .
   ports:
   - target: 8080
     published: 8080
     protocol: tcp
   volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - jenkins-volume:/var/jenkins_home
    - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
volumes:
 jenkins-volume:
 
